### PR TITLE
A much smaller skyline image

### PR DESCRIPTION
**Pull request by acme**
This commit has a much smaller skyline image (148KB -> 6KB). This will load much faster for users. This won't look bad, as browsers blur images that they upscale.

Before:
image

After:
image

### CODE REVIEW

**Comment by leejo** [comment]
Hey @acme - this looks pretty bad on my retina screen - can we maybe not compress so much? I think 20 or 30kb should be ok.

**Comment by acme** [comment]
Do you have statistics on what devices people use to visit the site?

**Comment by leejo** [comment]
> Do you have statistics on what devices people use to visit the site?

I don't, and I don't have access to the server logs either.

**Comment by acme** [comment]
I've increased the resolution of the image, it's now 25KB. How's that?

**Comment by leejo** [comment]
Looks much better 👍 . Merging!

**Pull request merged**
